---
version: '3.0'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:5.4.0
    volumes:
      - ./logstash/conf/logstash.conf/:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - elastic-stack

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic-stack




  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    ports: [ '5601:5601' ]
    networks:
      - elastic-stack

networks:
  elastic-stack:

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
